import { bySlug } from '../data/products'

export type RenderView = 'hero' | 'front' | 'side' | 'back'

/**
 * Filename suffix for a configuration whose geometry differs from the product's
 * default (currently: armrests on/off). Empty for the default shape.
 */
export function variantSuffix(slug: string, config?: string) {
  const p = bySlug(slug)
  if (!p || !config) return ''
  const cfg = p.configs.find((c) => c.id === config)
  if (!cfg || cfg.arms === p.configs[0].arms) return ''
  return cfg.arms ? '--arms' : '--noarms'
}

/**
 * Static product imagery. Real photography supplied in the product data takes
 * precedence; otherwise we fall back to the pre-rendered high-resolution images
 * (generated by /studio?render=1).
 */
export const fallbackSrc = (slug: string, color: string, view: RenderView = 'hero', config?: string) => {
  const custom = bySlug(slug)?.images?.[color]
  if (custom) return custom
  return `${import.meta.env.BASE_URL}renders/${slug}--${color}${view === 'hero' ? variantSuffix(slug, config) : ''}--${view}.webp`
}
